services:
  mongo:
    image: bitnami/mongodb:6.0.6
    environment:
      # replicaset required 
      - MONGODB_REPLICA_SET_MODE=primary
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - shared
    restart: on-failure

  minio:
    image: bitnami/minio
    environment:
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=CHANGEME123
      - MINIO_DEFAULT_BUCKETS=repertoire:public
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
    networks:
      - shared
    restart: on-failure

networks:
  shared:
    driver: bridge

volumes:
  mongo:
  minio: