services:
  mongodb:
    image: bitnami/mongodb:6.0.6
    # replicaset required for changestream to be enabled
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - service-network
    restart: always

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=CHANGEME123
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio:/data
    networks:
      - service-network

networks:
  service-network:
    driver: bridge

volumes:
  mongo:
  minio: